[package]
name = "p16_cbc_bit_flipping"
version = "0.1.0"
authors = ["Devon Hollowood <devonhollowood@gmail.com>"]

[[bin]]

name = "p16_cbc_bit_flipping"

[dependencies]
rust-crypto = "*"
rand = "*"
