[package]

name = "p10_implement_CBC"
version = "0.1.0"
authors = [ "Devon Hollowood <devonhollowood@gmail.com>" ]

[[bin]]

name = "p10_implement_CBC"

[dependencies]
rustc-serialize = "0.2"
rust-crypto = "*"
