[package]

name = "p12_ECB_crack_simple"
version = "0.1.0"
authors = [ "Devon Hollowood <devonhollowood@gmail.com>" ]

[[bin]]

name = "p12_ecb_crack_simple"

[dependencies]
rustc-serialize = "*"
rust-crypto = "*"
rand = "*"
