[package]

name = "p11_ECB_CBC_oracle"
version = "0.1.0"
authors = [ "Devon Hollowood <devonhollowood@gmail.com>" ]

[[bin]]

name = "p11_ECB_CBC_oracle"

[dependencies]
rand = "0.2"
rust-crypto = "*"
