[package]

name = "p13_ecb_cut_and_paste"
version = "0.1.0"
authors = [ "Devon Hollowood <devonhollowood@gmail.com>" ]

[[bin]]

name = "p13_ecb_cut_and_paste"

[dependencies]
rust-crypto = "*"
rand = "*"
regex = "*"
