[package]

name = "p14_ecb_crack_hard"
version = "0.1.0"
authors = [ "Devon Hollowood <devonhollowood@gmail.com>" ]

[[bin]]

name = "p12_ecb_crack_hard"

[dependencies]
rustc-serialize = "*"
rust-crypto = "*"
rand = "*"
